server:
  port: 9500
  servlet:
    context-path: /im

spring:
#  component:
#    scan:
#      base-packages: com.parent.common.log
  application:
    name: im
#  profiles:
#    active: test
  main:
    allow-bean-definition-overriding: true
    #防止循环依赖
    allow-circular-references: true
#关闭security默认过滤器
security:
  ignored: none

knife4j:
#  cors: true
#  enable: true
  setting:
    enable-dynamic-parameter: true
  #是否开启swagger登录验证
  basic:
    #enable: false
    username: root
    password: root

springdoc:
  api-docs:
    path: /v3/api-docs
  open:
    default-group-configs:
      enable: true
  group-configs:
    - group: "test"
      paths-to-match:
        - "/test/**"
  swagger-ui:
    operations-sorter: alpha
    path: /swagger-ui.html
    tags-sorter: alpha

mybatis-plus:
  type-aliases-package: com.minimalism.im,com.minimalism.user
  # 设置Mapper文件位置
  mapper-locations: classpath:mapper/*.xml, classpath:mapper/**/*.xml
  #配置
  configuration:
    # 使用JDBC的getGeneratedKeys，获取数据库自增主键值
    use-generated-keys: true
    # 使用列别名
    use-column-label: true
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
#logstash:
#  addr: 127.0.0.1:4560
logging:
  # 日志文件
#  file:
#    name: var/log/${spring.application.name}/${spring.profiles.active}/${spring.application.name}0.log
  # 日志等级
  level:
    root: error
    com.minimalism: debug
    com.baomidou.mybatisplus: debug

common:
    jwt:
      openFilter: true
      openInterceptor: false