<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.minimalism</groupId>
        <artifactId>minimalism</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>micro-sub-cores</artifactId>
    <packaging>pom</packaging>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.minimalism</groupId>
                <artifactId>framework-bom</artifactId>
                <version>${revision}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <modules>
        <module>basic-dict-core</module>
        <module>basic-dept-core</module>
        <module>basic-file-core</module>
        <module>basic-gateway-core</module>
        <module>basic-gen-core</module>
        <module>basic-im-core</module>
        <module>basic-job-core</module>
        <module>basic-quartz-core</module>
        <module>basic-user-core</module>
        <module>basic-validate-core</module>
        <module>basic-websocket-core</module>
    </modules>

</project>