spring:
  datasource:
    dynamic:
      # 开启seata代理
      seata: ${seata.enabled}
# seata配置
seata:
  enabled: true
  # Seata 应用编号，默认为 ${spring.application.name}
  # application-id: seata-server
  # Seata 事务组编号，用于 TC 集群名
  tx-service-group: default_tx_group
  #tx-service-group: ${spring.application.name}-group
  # 关闭自动代理
  enable-auto-data-source-proxy: false
  # 服务配置项
  service:
    grouplist:
      default: 127.0.0.1:8091
    # 虚拟组和分组的映射
    vgroup-mapping:
      default_tx_group: default
      #ruoyi-system-group: default
      # 分组和 Seata 服务的映射
      # grouplist:  # 仅注册中心为file时使用
      # default: 127.0.0.1:8091

  registry:
    type: nacos
    nacos:
      server-addr: ${nacos.discovery.server-addr}
      group: ${seata-server.discovery.group}
      namespace: ${seata-server.discovery.namespace}
  config:
    type: nacos
    nacos:
      server-addr: ${nacos.config.server-addr}
      group: ${seata-server.config.group}
      namespace: ${seata-server.config.namespace}


